// https://keycode.info/

/**
 * Keyboard Event `key` values. These are the string representations of the keys pressed.
 * This object can be used in other parts of the application to handle keyboard input and prevent hard-coded strings throughout.
 */
export const key = {
	ALT: "Alt",
	ARROW_DOWN: "ArrowDown",
	ARROW_LEFT: "ArrowLeft",
	ARROW_RIGHT: "ArrowRight",
	ARROW_UP: "ArrowUp",
	BACKSPACE: "Backspace",
	CAPS_LOCK: "CapsLock",
	CONTROL: "Control",
	DELETE: "Delete",
	HOME: "Home",
	END: "End",
	ENTER: "Enter",
	ESCAPE: "Escape",
	F1: "F1",
	F2: "F2",
	F3: "F3",
	F4: "F4",
	F5: "F5",
	F6: "F6",
	F7: "F7",
	F8: "F8",
	F9: "F9",
	F10: "F10",
	F11: "F11",
	F12: "F12",
	META: "Meta",
	PAGE_DOWN: "PageDown",
	PAGE_UP: "PageUp",
	SHIFT: "Shift",
	SPACE: " ",
	TAB: "Tab",
	CTRL: "Control",
	A: "a",
	E: "e",
	P: "p",
	PI: "π",
	ZERO: "0",
	ONE: "1",
	TWO: "2",
	THREE: "3",
	FOUR: "4",
	FIVE: "5",
	SIX: "6",
	SEVEN: "7",
	EIGHT: "8",
	NINE: "9",
	PLUS: "+",
	MINUS: "-",
	ASTERISK: "*",
	SQUARE: "²",
	SLASH: "/",
	COMMA: ",",
	OPEN_P: "(",
	CLOSE_P: ")",
};

/**
 * Keyboard Event `code` values. These are the physical keys pressed on the keyboard eg. on an AZERTY keyboard pressing A gives a KeyQ code
 */
export const code = {
	ARROW_DOWN: "ArrowDown",
	ARROW_LEFT: "ArrowLeft",
	ARROW_RIGHT: "ArrowRight",
	ARROW_UP: "ArrowUp",
	BACKSPACE: "Backspace",
	CAPS_LOCK: "CapsLock",
	DELETE: "Delete",
	END: "End",
	ENTER: "Enter",
	ESCAPE: "Escape",
	PAGE_DOWN: "PageDown",
	PAGE_UP: "PageUp",
	SPACE: "Space",
	TAB: "Tab",
	KEY_Q: "KeyQ",
	KEY_W: "KeyW",
	KEY_E: "KeyE",

	KEY_A: "KeyA",
	KEY_S: "KeyS",
	KEY_D: "KeyD",
};
